


/*------ GERASYS.TI 01/03/2018 15:52:07 --------*/

CREATE SEQUENCE GEN_ESOCIAL_EVENTO_S1000;




/*------ GERASYS.TI 01/03/2018 18:32:43 --------*/

CREATE TABLE CONFIG_ESOCIAL (
    ID_CONFIG_ORGAO "INTEGER" NOT NULL,
    ID_UNID_GESTORA "INTEGER",
    CONTADOR_NOME "VARCHAR(50)",
    CONTADOR_CPF "VARCHAR(11)",
    CONTADOR_FONEFIXO "VARCHAR(10)",
    CONTADOR_FONECELULAR "VARCHAR(11)",
    CONTADOR_EMAIL "VARCHAR(60)",
    NAT_JURIDICA "CHAR(5)",
    NRO_SIAFI "VARCHAR(8)",
    SUBTETO_VENCTO_TIPO "CHAR(1)",
    SUBTETO_VENCTO_VALOR "NUMERIC(15,2)",
    POSSUI_RPPS "CHAR(1)" DEFAULT 'N' NOT NULL);

ALTER TABLE CONFIG_ESOCIAL
ADD CONSTRAINT PK_CONFIG_ESOCIAL
PRIMARY KEY (ID_CONFIG_ORGAO);

COMMENT ON COLUMN CONFIG_ESOCIAL.NAT_JURIDICA IS
'Natureza Juridica:
Anexo I dos Leiautes do eSocial versao 2.4 - Tabela 21';

COMMENT ON COLUMN CONFIG_ESOCIAL.NRO_SIAFI IS
'Preencher com o numero SIAFI (Sistema Integrado de Administracao Financeira), caso seja orgao publico usuario do sistema.';

COMMENT ON COLUMN CONFIG_ESOCIAL.SUBTETO_VENCTO_TIPO IS
'Tipo do Subteto:
1 - Executivo
2 - Judiciario
3 - Legislativo
9 - Todos os poderes';

COMMENT ON COLUMN CONFIG_ESOCIAL.POSSUI_RPPS IS
'Informar se o entindade publica possui Regime Proprio de Previdencia Social - RPPS:
N - Nao
S - Sim';




/*------ GERASYS.TI 01/03/2018 18:33:04 --------*/

ALTER TABLE CONFIG_ESOCIAL ALTER COLUMN SUBTETO_VENCTO_TIPO
SET DEFAULT '9'
;




/*------ GERASYS.TI 01/03/2018 18:33:10 --------*/

update RDB$RELATION_FIELDS set
RDB$NULL_FLAG = 1
where (RDB$FIELD_NAME = 'SUBTETO_VENCTO_TIPO') and
(RDB$RELATION_NAME = 'CONFIG_ESOCIAL')
;




/*------ GERASYS.TI 01/03/2018 18:34:20 --------*/

ALTER TABLE CONFIG_ESOCIAL
ADD CONSTRAINT FK_CONFIG_ESOCIAL_ORG
FOREIGN KEY (ID_CONFIG_ORGAO)
REFERENCES CONFIG_ORGAO(ID)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE CONFIG_ESOCIAL
ADD CONSTRAINT FK_CONFIG_ESOCIAL_UNG
FOREIGN KEY (ID_UNID_GESTORA)
REFERENCES UNID_GESTORA(ID)
ON DELETE CASCADE
ON UPDATE CASCADE;

GRANT ALL ON CONFIG_ESOCIAL TO "PUBLIC";



/*------ GERASYS.TI 02/03/2018 12:00:11 --------*/

COMMENT ON COLUMN CONFIG_ESOCIAL.NRO_SIAFI IS
'Preencher com o numero SIAFI (Sistema Integrado de Administracao Financeira), caso seja orgao publico usuario do sistema.

Pesquisar em: http://consulta.tesouro.fazenda.gov.br/ug_novosite/index_ug.asp';




/*------ GERASYS.TI 02/03/2018 12:04:09 --------*/

ALTER SEQUENCE GEN_ESOCIAL_EVENTO_S1000 RESTART WITH 0;

