UPDATE ESTADO_CIVIL SET 
    ID_ESOCIAL = 1
WHERE (ID = 1);

UPDATE ESTADO_CIVIL SET 
    ID_ESOCIAL = 2
WHERE (ID = 2);

UPDATE ESTADO_CIVIL SET 
    ID_ESOCIAL = 5
WHERE (ID = 3);

UPDATE ESTADO_CIVIL SET 
    ID_ESOCIAL = 4
WHERE (ID = 4);

UPDATE ESTADO_CIVIL SET 
    ID_ESOCIAL = 3
WHERE (ID = 5);

UPDATE ESTADO_CIVIL SET 
    ID_ESOCIAL = 2
WHERE (ID = 6);

UPDATE ESTADO_CIVIL SET 
    ID_ESOCIAL = 1
WHERE (ID = 0);


COMMIT WORK;
