UPDATE NACIONALIDADE SET 
    ID_ESOCIAL = '063'
WHERE (ID = 21);

UPDATE NACIONALIDADE SET 
    ID_ESOCIAL = '097'
WHERE (ID = 22);

UPDATE NACIONALIDADE SET 
    ID_ESOCIAL = '105'
WHERE (ID = 10);

UPDATE NACIONALIDADE SET 
    ID_ESOCIAL = '158'
WHERE (ID = 23);

UPDATE NACIONALIDADE SET 
    ID_ESOCIAL = '169'
WHERE (ID = 26);

UPDATE NACIONALIDADE SET 
    ID_ESOCIAL = '239'
WHERE (ID = 27);


COMMIT WORK;
