UPDATE ESCOLARIDADE SET 
    ID_ESOCIAL = '01'
WHERE (ID = 1);

UPDATE ESCOLARIDADE SET 
    ID_ESOCIAL = '02'
WHERE (ID = 2);

UPDATE ESCOLARIDADE SET 
    ID_ESOCIAL = '04'
WHERE (ID = 3);

UPDATE ESCOLARIDADE SET 
    ID_ESOCIAL = '05'
WHERE (ID = 4);

UPDATE ESCOLARIDADE SET 
    ID_ESOCIAL = '06'
WHERE (ID = 5);

UPDATE ESCOLARIDADE SET 
    ID_ESOCIAL = '07'
WHERE (ID = 6);

UPDATE ESCOLARIDADE SET 
    ID_ESOCIAL = '08'
WHERE (ID = 7);

UPDATE ESCOLARIDADE SET 
    ID_ESOCIAL = '09'
WHERE (ID = 8);

UPDATE ESCOLARIDADE SET 
    ID_ESOCIAL = '11'
WHERE (ID = 9);

UPDATE ESCOLARIDADE SET 
    ID_ESOCIAL = '12'
WHERE (ID = 10);

UPDATE ESCOLARIDADE SET 
    ID_ESOCIAL = '01'
WHERE (ID = 0);


COMMIT WORK;
