UPDATE TAB_RACA_COR SET 
    ID_ESOCIAL = 5
WHERE (ID = 1);

UPDATE TAB_RACA_COR SET 
    ID_ESOCIAL = 1
WHERE (ID = 2);

UPDATE TAB_RACA_COR SET 
    ID_ESOCIAL = 2
WHERE (ID = 4);

UPDATE TAB_RACA_COR SET 
    ID_ESOCIAL = 4
WHERE (ID = 6);

UPDATE TAB_RACA_COR SET 
    ID_ESOCIAL = 3
WHERE (ID = 8);

UPDATE TAB_RACA_COR SET 
    ID_ESOCIAL = 6
WHERE (ID = 9);


COMMIT WORK;
