UPDATE OR INSERT INTO TAB_HORARIO (ID, TIPO_TURNO, HORA_ENTRADA1, HORA_SAIDA, HORA_ENTRADA2, HORA_SAIDA2, TIPO_OPERACAO, PERMITE_FLEXIBILIDADE, TIPO_INTERVALO, DURACAO_JORNADA, DURACAO_INTERVALO, INTERVALO_INICIO, INTERVALO_FINAL)
                           VALUES (1, '1', '0800', '1100', '1300', '1800', 'I', 'N', '1', '480 ', '120 ', '1100', '1300')
                         MATCHING (ID);
UPDATE OR INSERT INTO TAB_HORARIO (ID, TIPO_TURNO, HORA_ENTRADA1, HORA_SAIDA, HORA_ENTRADA2, HORA_SAIDA2, TIPO_OPERACAO, PERMITE_FLEXIBILIDADE, TIPO_INTERVALO, DURACAO_JORNADA, DURACAO_INTERVALO, INTERVALO_INICIO, INTERVALO_FINAL)
                           VALUES (2, '1', '0800', '1200', NULL, NULL, 'I', 'N', '1', '240 ', NULL, NULL, NULL)
                         MATCHING (ID);
UPDATE OR INSERT INTO TAB_HORARIO (ID, TIPO_TURNO, HORA_ENTRADA1, HORA_SAIDA, HORA_ENTRADA2, HORA_SAIDA2, TIPO_OPERACAO, PERMITE_FLEXIBILIDADE, TIPO_INTERVALO, DURACAO_JORNADA, DURACAO_INTERVALO, INTERVALO_INICIO, INTERVALO_FINAL)
                           VALUES (3, '1', '0700', '1100', '1200', '1900', 'I', 'N', '1', '660 ', '60  ', '1100', '1200')
                         MATCHING (ID);

COMMIT WORK;