INSERT INTO ESOCIAL_FATOR_RISCO (CODIGO, GRUPO, DESCRICAO)
                         VALUES ('0101000', NULL, 'FÍSICO');
INSERT INTO ESOCIAL_FATOR_RISCO (CODIGO, GRUPO, DESCRICAO)
                         VALUES ('0101001', '0101000', 'Infrassom e sons de baixa frequência');
INSERT INTO ESOCIAL_FATOR_RISCO (CODIGO, GRUPO, DESCRICAO)
                         VALUES ('0101999', '0101000', 'Outros');
INSERT INTO ESOCIAL_FATOR_RISCO (CODIGO, GRUPO, DESCRICAO)
                         VALUES ('0201000', NULL, 'QUÍMICOS');
INSERT INTO ESOCIAL_FATOR_RISCO (CODIGO, GRUPO, DESCRICAO)
                         VALUES ('0201001', '0201000', 'Acetaldeído');
INSERT INTO ESOCIAL_FATOR_RISCO (CODIGO, GRUPO, DESCRICAO)
                         VALUES ('0201999', '0201000', 'Outros');
INSERT INTO ESOCIAL_FATOR_RISCO (CODIGO, GRUPO, DESCRICAO)
                         VALUES ('0301000', NULL, 'BIOLÓGICO');
INSERT INTO ESOCIAL_FATOR_RISCO (CODIGO, GRUPO, DESCRICAO)
                         VALUES ('0301001', '0301000', 'Trabalho ou operações, em contato permanente com pacientes');
INSERT INTO ESOCIAL_FATOR_RISCO (CODIGO, GRUPO, DESCRICAO)
                         VALUES ('0301999', '0301000', 'Outros');
INSERT INTO ESOCIAL_FATOR_RISCO (CODIGO, GRUPO, DESCRICAO)
                         VALUES ('0901000', NULL, 'AUSÊNCIA DE FATORES DE RISCO');
INSERT INTO ESOCIAL_FATOR_RISCO (CODIGO, GRUPO, DESCRICAO)
                         VALUES ('0901001', '0901000', 'Ausência de Fator de Risco');

COMMIT WORK;
